### ISSUE TITLE
Add or link to Ingress logo font

### ISSUE THREAD

**Issue by marijnvdwerf** [cr0ybot/ingress-logos#6]
After redrawing the entire logo font based on the Ingress Report videos, I found out they're using http://www.dafont.com/amarillo-usaf.font. Might be nice to either mirror or add a link to this font.

**Comment by corvock** [comment]
From what i have found, the font in game is called Coda .. http://www.google.com/fonts/specimen/Coda

**Comment by badchy** [comment]
pls font card color blue ? http://prntscr.com/9vif1y
